# Generated by Django 5.1.2 on 2024-11-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('technologies', models.CharField(help_text='Technologies used in the project', max_length=255)),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Main image for the project', null=True, upload_to='project_images/')),
                ('live_link', models.URLField(blank=True, help_text='Link to the live project, if available', null=True)),
                ('github_link', models.URLField(blank=True, help_text="Link to the project's GitHub repository", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the project was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the project details were last updated')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional image for the project', upload_to='project_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Associated project for this image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
