# Generated by Django 5.1.2 on 2024-11-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technology_remove_project_technologies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
