# Generated by Django 5.1.2 on 2024-11-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_technology_options'),
        ('technologies', '0002_alter_technology_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in the project', related_name='projects', to='technologies.technology'),
        ),
    ]
