# Generated by Django 5.1.2 on 2024-11-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='Name of the educational institution', max_length=255, verbose_name='Institution Name')),
                ('degree', models.CharField(help_text='Name of the degree or qualification earned', max_length=255, verbose_name='Degree')),
                ('field_of_study', models.CharField(blank=True, help_text='Field of study or major', max_length=255, verbose_name='Field of Study')),
                ('start_date', models.DateField(blank=True, help_text='When you started this education', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='When you completed this education (leave blank if ongoing)', null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, help_text='Additional information about your studies, projects, or achievements', verbose_name='Description')),
                ('grade', models.CharField(blank=True, help_text='Your final grade or GPA (optional)', max_length=10, verbose_name='Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
    ]
