# Generated by Django 5.1.2 on 2024-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company where you worked', max_length=255, verbose_name='Company Name')),
                ('job_title', models.CharField(help_text='Your job title at the company', max_length=255, verbose_name='Job Title')),
                ('start_date', models.DateField(help_text='The date you started working at the company', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='The date you stopped working at the company', null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, help_text='A brief description of your responsibilities and achievements', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the experience entry was created', verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the experience entry was last updated', verbose_name='Date Updated')),
            ],
        ),
    ]
