# Generated by Django 5.1.2 on 2024-11-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
