# Generated by Django 5.1.2 on 2024-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the technology', max_length=100)),
                ('icon', models.ImageField(help_text='Icon or image representing the technology', upload_to='technology_icons/')),
                ('description', models.TextField(blank=True, help_text='Brief description of the technology')),
                ('proficiency', models.IntegerField(default=0, help_text='Expertise percentage (0 to 100)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the technology entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the technology entry was last updated')),
            ],
        ),
    ]
