# Generated by Django 5.1.2 on 2024-11-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_alter_technology_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='Name of the technology type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the technology type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the technology type entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the technology type entry was last updated')),
            ],
            options={
                'verbose_name': 'Technology Type',
                'verbose_name_plural': 'Technology Types',
            },
        ),
        migrations.AddField(
            model_name='technology',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type of the technology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='technologies.tech_type'),
        ),
    ]
